# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
# Resource IDs and attributes exposed for the customer root module, and for
# anything needing a value Terraform generated (the reporting integration
# credentials have to be entered into that product by hand).
#
# `sensitive = true` keeps an output out of plan and apply logs. It does NOT keep
# it out of state, which is plain text and must be treated as a secret.
# -----------------------------------------------------------------------------

# --- API Clients ------------------------------------------------------------

output "api_client_id" {
  description = "ID of the Managed Protect API client used for Jamf Pro registration"
  value       = jamfprotect_api_client.managed_protect_standard.id
}

output "insights_api_client_id" {
  description = "ID of the reporting integration API client"
  value       = jamfprotect_api_client.insights.id
}

output "insights_api_client_secret" {
  description = "Password for the reporting integration API client. Generated by Terraform and entered into the reporting product manually."
  value       = jamfprotect_api_client.insights.password
  sensitive   = true
}

# --- Jamf Pro ---------------------------------------------------------------

output "jamf_pro_server_url" {
  description = "Jamf Pro server URL for this tenant, resolved through the platform environment"
  value       = data.jamfplatform_pro_jamf_pro_server_url.current.url
}

# --- Roles ------------------------------------------------------------------

output "role_id" {
  description = "ID of the built-in Read Only role in this tenant"
  value       = local.read_only_role_id
}

output "insights_role_id" {
  description = "ID of the reporting integration role"
  value       = jamfprotect_role.insights.id
}

# --- Action Configuration ---------------------------------------------------

output "action_configuration_id" {
  description = "ID of the Managed Protect Standard action configuration"
  value       = jamfprotect_action_configuration.managed_protect_standard.id
}

# --- Analytics --------------------------------------------------------------

output "analytic_id" {
  description = "ID of the Managed Protect Quarantine custom analytic"
  value       = jamfprotect_analytic.managed_protect_quarantine.id
}

output "analytic_set_id" {
  description = "ID of the Managed Protect Standard analytic set"
  value       = jamfprotect_analytic_set.managed_protect_standard.id
}

# --- Plans ------------------------------------------------------------------

output "plan_id" {
  description = "ID of the threat prevention plan (created on every tier)"
  value       = jamfprotect_plan.managed_protect_standard.id
}

output "enhanced_plan_id" {
  description = "ID of the threat prevention + device controls plan. Null when product_tier is standard."
  value       = local.enable_device_controls ? jamfprotect_plan.managed_protect_enhanced[0].id : null
}

# --- Device Controls --------------------------------------------------------

output "removable_storage_control_set_id" {
  description = "ID of the removable storage control set. Null when product_tier is standard."
  value       = local.enable_device_controls ? jamfprotect_removable_storage_control_set.managed_protect_enhanced[0].id : null
}

# --- Exception Sets ---------------------------------------------------------

output "customer_exception_set_ids" {
  description = "Map of per-customer exception set names to their IDs"
  value       = { for k, v in jamfprotect_exception_set.customer : k => v.id }
}
